### ISSUE TITLE
Row does not contain primary id column data.

### ISSUE THREAD

**Issue by riskar** [efabrica-team/nette-database-repository#7]
We have randomly very offten this error when creating new record:

`Nette\InvalidStateException: Row does not contain primary id column data. in /builds/web-components/onair/vendor/nette/database/src/Database/Table/ActiveRow.php:92`

It's possible that somewhere is missing argument `$throw = false`? problem is in `VersionEventSubscriber.php:148`.

**Comment by riki137** [comment]
Could you please give me any means to reproduce this problem? Last time i asked, we only encountered it in CI clicker. I can try to blind fix it, but it would be great if we knew the exact source of the problem.
